language: rust
#cache: cargo

os:
 - linux
 - windows
 - osx

arch:
- amd64
- arm64

rust:
  - stable
  - nightly

env:
  - RUST_BACKTRACE=1

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
