language: rust
os:
  - linux
  - windows
  - osx
arch:
  - amd64
  - arm64
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
#  - cargo test --verbose