[package]
name = "rbdc-pg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.7.6"



[dev-dependencies]
tokio = {version="1",features = ["full"]}