name: 'issue-translator'
on: 
  issue_comment:
    types: [created]
  issues:
    types: [opened]
    
jobs:
   build:
     runs-on: unbutu-latest
     steps:
        - uses: usthe/issues-translate-action@v2.7
          with:
            # The issue comment bot GITHUB_TOKEN.
            BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
            # The issue comment bot github login name.
            BOT_LOGIN_NAME: Issues-translate-bot
            # Is need modify issue title, true or false, default false.
            IS_MODIFY_TITLE: true
            # Custom bot note message.
            CUSTOM_BOT_NOTE: Issues-translate
